# Generated by Django 4.2.8 on 2023-12-21 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subtitle',
            table='Subtitle',
        ),
        migrations.AlterModelTable(
            name='upload',
            table='Upload',
        ),
        migrations.AlterModelTable(
            name='userupload',
            table='UserUpload',
        ),
        migrations.AlterModelTable(
            name='video',
            table='Video',
        ),
    ]
