# Generated by Django 4.2.8 on 2023-12-27 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_upload_path_image_alter_upload_path_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='path_image',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='title_video',
        ),
    ]
