# Generated by Django 4.2.8 on 2023-12-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_upload_path_image_remove_upload_title_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='path_video',
            field=models.FileField(upload_to='Files/'),
        ),
    ]
