# Generated by Django 4.2.8 on 2023-12-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_upload_path_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='path_image',
            field=models.FileField(null=True, upload_to='Files/'),
        ),
        migrations.AddField(
            model_name='upload',
            name='title_video',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
