# Generated by Django 4.2.8 on 2023-12-14 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.CharField(default='client', max_length=50)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
