# Generated by Django 4.2.8 on 2023-12-18 16:53

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_users'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('empAuth_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
